window.githubUserData = [
	{
		"login": "founddrama",
		"id": 65650,
		"avatar_url": "https://secure.gravatar.com/avatar/e773170f04213ddf22f4d440736c0b61?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "e773170f04213ddf22f4d440736c0b61",
		"url": "https://api.github.com/users/founddrama",
		"html_url": "https://github.com/founddrama",
		"followers_url": "https://api.github.com/users/founddrama/followers",
		"following_url": "https://api.github.com/users/founddrama/following{/other_user}",
		"gists_url": "https://api.github.com/users/founddrama/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/founddrama/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/founddrama/subscriptions",
		"organizations_url": "https://api.github.com/users/founddrama/orgs",
		"repos_url": "https://api.github.com/users/founddrama/repos",
		"events_url": "https://api.github.com/users/founddrama/events{/privacy}",
		"received_events_url": "https://api.github.com/users/founddrama/received_events",
		"type": "User",
		"name": "Rob Friesel",
		"company": null,
		"blog": "http://blog.founddrama.net/",
		"location": "Essex Junction VT",
		"email": "rob@founddrama.net",
		"hireable": false,
		"bio": "Front-end developer specializing in\r\n  - JavaScript\r\n  - Groovy/Grails\r\n",
		"public_repos": 34,
		"followers": 11,
		"following": 19,
		"created_at": "2009-03-22T00:02:56Z",
		"updated_at": "2013-06-20T16:17:04Z",
		"public_gists": 65
	},
	{
		"login": "ryangardner",
		"id": 235349,
		"avatar_url": "https://secure.gravatar.com/avatar/6033c9162c6d49cba3c163ad4f224564?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "6033c9162c6d49cba3c163ad4f224564",
		"url": "https://api.github.com/users/ryangardner",
		"html_url": "https://github.com/ryangardner",
		"followers_url": "https://api.github.com/users/ryangardner/followers",
		"following_url": "https://api.github.com/users/ryangardner/following{/other_user}",
		"gists_url": "https://api.github.com/users/ryangardner/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/ryangardner/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/ryangardner/subscriptions",
		"organizations_url": "https://api.github.com/users/ryangardner/orgs",
		"repos_url": "https://api.github.com/users/ryangardner/repos",
		"events_url": "https://api.github.com/users/ryangardner/events{/privacy}",
		"received_events_url": "https://api.github.com/users/ryangardner/received_events",
		"type": "User",
		"name": "Ryan Gardner",
		"company": "Dealer.com",
		"blog": "http://ryebrye.com/blog",
		"location": "Burlington, VT",
		"email": null,
		"hireable": false,
		"bio": "",
		"public_repos": 15,
		"followers": 0,
		"following": 1,
		"created_at": "2010-04-01T23:00:47Z",
		"updated_at": "2013-06-20T17:52:40Z",
		"public_gists": 0
	},
	{
		"login": "ddcjackm",
		"id": 264929,
		"avatar_url": "https://secure.gravatar.com/avatar/6018030d6aea4128a7920081c8b79f1b?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "6018030d6aea4128a7920081c8b79f1b",
		"url": "https://api.github.com/users/ddcjackm",
		"html_url": "https://github.com/ddcjackm",
		"followers_url": "https://api.github.com/users/ddcjackm/followers",
		"following_url": "https://api.github.com/users/ddcjackm/following{/other_user}",
		"gists_url": "https://api.github.com/users/ddcjackm/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/ddcjackm/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/ddcjackm/subscriptions",
		"organizations_url": "https://api.github.com/users/ddcjackm/orgs",
		"repos_url": "https://api.github.com/users/ddcjackm/repos",
		"events_url": "https://api.github.com/users/ddcjackm/events{/privacy}",
		"received_events_url": "https://api.github.com/users/ddcjackm/received_events",
		"type": "User",
		"public_repos": 2,
		"followers": 0,
		"following": 0,
		"created_at": "2010-05-04T21:34:58Z",
		"updated_at": "2013-04-05T04:21:41Z",
		"public_gists": 0
	},
	{
		"login": "nhusher",
		"id": 376978,
		"avatar_url": "https://secure.gravatar.com/avatar/d1e6db24f6543a6086a799d068eb78d1?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "d1e6db24f6543a6086a799d068eb78d1",
		"url": "https://api.github.com/users/nhusher",
		"html_url": "https://github.com/nhusher",
		"followers_url": "https://api.github.com/users/nhusher/followers",
		"following_url": "https://api.github.com/users/nhusher/following{/other_user}",
		"gists_url": "https://api.github.com/users/nhusher/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/nhusher/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/nhusher/subscriptions",
		"organizations_url": "https://api.github.com/users/nhusher/orgs",
		"repos_url": "https://api.github.com/users/nhusher/repos",
		"events_url": "https://api.github.com/users/nhusher/events{/privacy}",
		"received_events_url": "https://api.github.com/users/nhusher/received_events",
		"type": "User",
		"name": "Nicholas Husher",
		"company": "Dealer.com",
		"blog": "nickol.us",
		"location": "Vermont",
		"email": null,
		"hireable": false,
		"bio": null,
		"public_repos": 15,
		"followers": 1,
		"following": 6,
		"created_at": "2010-08-26T14:44:52Z",
		"updated_at": "2013-06-18T23:34:15Z",
		"public_gists": 103
	},
	{
		"login": "jdpgrailsdev",
		"id": 450956,
		"avatar_url": "https://secure.gravatar.com/avatar/528dfe68e5fb87f5d3aa816152ae604c?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "528dfe68e5fb87f5d3aa816152ae604c",
		"url": "https://api.github.com/users/jdpgrailsdev",
		"html_url": "https://github.com/jdpgrailsdev",
		"followers_url": "https://api.github.com/users/jdpgrailsdev/followers",
		"following_url": "https://api.github.com/users/jdpgrailsdev/following{/other_user}",
		"gists_url": "https://api.github.com/users/jdpgrailsdev/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/jdpgrailsdev/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/jdpgrailsdev/subscriptions",
		"organizations_url": "https://api.github.com/users/jdpgrailsdev/orgs",
		"repos_url": "https://api.github.com/users/jdpgrailsdev/repos",
		"events_url": "https://api.github.com/users/jdpgrailsdev/events{/privacy}",
		"received_events_url": "https://api.github.com/users/jdpgrailsdev/received_events",
		"type": "User",
		"name": "Jonathan Pearlin",
		"company": "Dealer.com",
		"blog": "http://jonathan-whywecanthavenicethings.blogspot.com/",
		"location": "Burlington, VT, USA",
		"email": "jpearlin1@gmail.com",
		"hireable": false,
		"bio": null,
		"public_repos": 22,
		"followers": 1,
		"following": 0,
		"created_at": "2010-10-23T14:23:21Z",
		"updated_at": "2013-06-17T12:49:53Z",
		"public_gists": 1
	},
	{
		"login": "froderick",
		"id": 635246,
		"avatar_url": "https://secure.gravatar.com/avatar/8dc6f43273c4cd7898f7fa90562eb62d?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "8dc6f43273c4cd7898f7fa90562eb62d",
		"url": "https://api.github.com/users/froderick",
		"html_url": "https://github.com/froderick",
		"followers_url": "https://api.github.com/users/froderick/followers",
		"following_url": "https://api.github.com/users/froderick/following{/other_user}",
		"gists_url": "https://api.github.com/users/froderick/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/froderick/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/froderick/subscriptions",
		"organizations_url": "https://api.github.com/users/froderick/orgs",
		"repos_url": "https://api.github.com/users/froderick/repos",
		"events_url": "https://api.github.com/users/froderick/events{/privacy}",
		"received_events_url": "https://api.github.com/users/froderick/received_events",
		"type": "User",
		"public_repos": 0,
		"followers": 0,
		"following": 0,
		"created_at": "2011-02-24T03:18:45Z",
		"updated_at": "2013-01-23T04:56:49Z",
		"public_gists": 0
	},
	{
		"login": "lgouger",
		"id": 710845,
		"avatar_url": "https://secure.gravatar.com/avatar/c1c68b9857a4835e05824864fe70e813?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "c1c68b9857a4835e05824864fe70e813",
		"url": "https://api.github.com/users/lgouger",
		"html_url": "https://github.com/lgouger",
		"followers_url": "https://api.github.com/users/lgouger/followers",
		"following_url": "https://api.github.com/users/lgouger/following{/other_user}",
		"gists_url": "https://api.github.com/users/lgouger/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/lgouger/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/lgouger/subscriptions",
		"organizations_url": "https://api.github.com/users/lgouger/orgs",
		"repos_url": "https://api.github.com/users/lgouger/repos",
		"events_url": "https://api.github.com/users/lgouger/events{/privacy}",
		"received_events_url": "https://api.github.com/users/lgouger/received_events",
		"type": "User",
		"name": "Larry Gouger",
		"company": null,
		"blog": null,
		"location": "California",
		"email": "lgouger@gmail.com",
		"hireable": false,
		"bio": null,
		"public_repos": 5,
		"followers": 1,
		"following": 0,
		"created_at": "2011-04-05T14:20:05Z",
		"updated_at": "2013-06-18T03:42:24Z",
		"public_gists": 0
	},
	{
		"login": "ellerycrane",
		"id": 784493,
		"avatar_url": "https://secure.gravatar.com/avatar/dcfdabd4cb437ff6883c778852bd7168?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "dcfdabd4cb437ff6883c778852bd7168",
		"url": "https://api.github.com/users/ellerycrane",
		"html_url": "https://github.com/ellerycrane",
		"followers_url": "https://api.github.com/users/ellerycrane/followers",
		"following_url": "https://api.github.com/users/ellerycrane/following{/other_user}",
		"gists_url": "https://api.github.com/users/ellerycrane/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/ellerycrane/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/ellerycrane/subscriptions",
		"organizations_url": "https://api.github.com/users/ellerycrane/orgs",
		"repos_url": "https://api.github.com/users/ellerycrane/repos",
		"events_url": "https://api.github.com/users/ellerycrane/events{/privacy}",
		"received_events_url": "https://api.github.com/users/ellerycrane/received_events",
		"type": "User",
		"public_repos": 0,
		"followers": 0,
		"following": 0,
		"created_at": "2011-05-12T18:43:50Z",
		"updated_at": "2013-06-17T14:30:15Z",
		"public_gists": 2
	},
	{
		"login": "newbeb",
		"id": 1584456,
		"avatar_url": "https://secure.gravatar.com/avatar/bf1e8daaaee60a04f6e977816c78671d?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "bf1e8daaaee60a04f6e977816c78671d",
		"url": "https://api.github.com/users/newbeb",
		"html_url": "https://github.com/newbeb",
		"followers_url": "https://api.github.com/users/newbeb/followers",
		"following_url": "https://api.github.com/users/newbeb/following{/other_user}",
		"gists_url": "https://api.github.com/users/newbeb/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/newbeb/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/newbeb/subscriptions",
		"organizations_url": "https://api.github.com/users/newbeb/orgs",
		"repos_url": "https://api.github.com/users/newbeb/repos",
		"events_url": "https://api.github.com/users/newbeb/events{/privacy}",
		"received_events_url": "https://api.github.com/users/newbeb/received_events",
		"type": "User",
		"name": "Brian Lloyd-Newberry",
		"company": null,
		"blog": "http://newbebweb.blogspot.com/",
		"location": "Burlington, VT",
		"email": null,
		"hireable": false,
		"bio": null,
		"public_repos": 2,
		"followers": 0,
		"following": 0,
		"created_at": "2012-03-28T18:06:11Z",
		"updated_at": "2013-01-23T13:20:58Z",
		"public_gists": 0
	},
	{
		"login": "aburnett",
		"id": 1906508,
		"avatar_url": "https://secure.gravatar.com/avatar/31ea22b18d7e703255bb4bdcd5032536?d=https….akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
		"gravatar_id": "31ea22b18d7e703255bb4bdcd5032536",
		"url": "https://api.github.com/users/aburnett",
		"html_url": "https://github.com/aburnett",
		"followers_url": "https://api.github.com/users/aburnett/followers",
		"following_url": "https://api.github.com/users/aburnett/following{/other_user}",
		"gists_url": "https://api.github.com/users/aburnett/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/aburnett/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/aburnett/subscriptions",
		"organizations_url": "https://api.github.com/users/aburnett/orgs",
		"repos_url": "https://api.github.com/users/aburnett/repos",
		"events_url": "https://api.github.com/users/aburnett/events{/privacy}",
		"received_events_url": "https://api.github.com/users/aburnett/received_events",
		"type": "User",
		"name": "Adam Burnett",
		"company": "Dealer.com",
		"blog": "www.thebur.net",
		"location": "Burlington, VT",
		"email": null,
		"hireable": false,
		"bio": null,
		"public_repos": 1,
		"followers": 0,
		"following": 0,
		"created_at": "2012-06-29T15:44:05Z",
		"updated_at": "2013-06-04T00:05:05Z",
		"public_gists": 0
	}
] 